#!/usr/bin/env python3

import subprocess
import sys
import json
import glob


dict1 = json.loads(subprocess.check_output(['./frequency'] + glob.glob(sys.argv[1])).decode("utf-8"))

dict2 = json.loads(subprocess.check_output(['./frequency'] + glob.glob(sys.argv[2])).decode("utf-8"))

print("Character, Rel. Freq. in " + sys.argv[1] + ", Rel. Freq. in " + sys.argv[2])

for char in set(list(dict1.keys()) + list(dict2.keys())):
	print(char + ", ", end="")
	if char in dict1:
		print(str(dict1[char][1]), end="")
	else:
		print(0, end="")
	print(", ", end="")
	if char in dict2:
		print(str(dict2[char][1]), end="")
	else:
		print(0, end="")
	print("")


